piVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "diskloca"
  labels:
    type: local
spec:
  capacity:
    storage: "20Gi" 
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-e0ae5266"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "diskcl"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
