apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: jnlp
      port: 50000
  selector:
    app: jenkins-app
  type: LoadBalancer
